# Generated by Django 5.2.17 on 2026-08-11 08:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0005_resync_role_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('member_added', "Ish maydoniga qo'shildingiz"), ('member_joined', "Jamoaga yangi a'zo qo'shildi"), ('member_removed', 'Ish maydonidan chiqarildingiz'), ('role_changed', "Rolingiz o'zgardi"), ('invitation_accepted', 'Taklif qabul qilindi'), ('task_assigned', 'Vazifa biriktirildi')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, default='', max_length=400)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'bildirishnoma',
                'verbose_name_plural': 'bildirishnomalar',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_notif_user_created'), models.Index(fields=['user', 'read_at'], name='idx_notif_user_read')],
            },
        ),
    ]
