# Generated by Django 5.2.17 on 2026-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, choices=[('project_manager', 'Loyiha menejeri'), ('developer', 'Dasturchi'), ('designer', 'Dizayner'), ('qa', 'Tester'), ('analyst', 'Analitik'), ('marketing', 'Marketolog'), ('other', 'Boshqa')], default='', max_length=20),
        ),
    ]
