# Generated by Django 5.2.17 on 2026-08-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_readonly',
            field=models.BooleanField(default=False),
        ),
    ]
