# Generated by Django 5.2.17 on 2026-08-07 12:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='#7B68EE', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('position', models.CharField(db_collation='C', db_index=True, max_length=64)),
                ('title', models.CharField(max_length=500)),
                ('description_html', models.TextField(blank=True, default='')),
                ('description_json', models.JSONField(blank=True, default=None, null=True)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low'), ('none', 'No priority')], db_index=True, default='none', max_length=7)),
                ('priority_order', models.PositiveSmallIntegerField(db_index=True, default=5, editable=False)),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('time_estimate_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(525600)])),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workspaces.tasklist')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workspaces.status')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_assignees',
                'ordering': ['assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', through='tasks.TaskAssignee', through_fields=('task', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to='tasks.task')),
            ],
            options={
                'db_table': 'task_tags',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='tasks.TaskTag', to='tasks.tag'),
        ),
        migrations.CreateModel(
            name='TaskWatcher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto_creator', 'Auto (creator)'), ('auto_assignee', 'Auto (assignee)'), ('auto_comment', 'Auto (commented)')], default='manual', max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_watchers', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_watches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_watchers',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_tasks', through='tasks.TaskWatcher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='idx_tag_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('name'), name='uniq_tag_name_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='taskassignee',
            index=models.Index(fields=['user', 'task'], name='idx_assignee_user_task'),
        ),
        migrations.AddConstraint(
            model_name='taskassignee',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_assignee'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['tag', 'task'], name='idx_tasktag_tag_task'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('task', 'tag'), name='uniq_task_tag'),
        ),
        migrations.AddIndex(
            model_name='taskwatcher',
            index=models.Index(fields=['user'], name='idx_watcher_user'),
        ),
        migrations.AddConstraint(
            model_name='taskwatcher',
            constraint=models.UniqueConstraint(fields=('task', 'user'), name='uniq_task_watcher'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['list', 'status', 'position'], name='idx_task_column_pos'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['list', 'deleted_at', 'archived'], name='idx_task_list_live'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['list', 'updated_at'], name='idx_task_list_updated'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='idx_task_due'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority_order'], name='idx_task_priority_order'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='idx_task_creator'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('list', 'status', 'position'), name='uniq_task_position_per_column'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('due_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='task_start_before_due'),
        ),
    ]
