# Generated by Django 5.2.17 on 2026-08-07 14:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assignee_added', 'Assignee added'), ('assignee_removed', 'Assignee removed'), ('priority_changed', 'Priority changed'), ('due_date_changed', 'Due date changed'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('restored', 'Restored')], db_index=True, max_length=16)),
                ('from_value', models.CharField(blank=True, max_length=255, null=True)),
                ('to_value', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_activities', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='tasks.task')),
            ],
            options={
                'db_table': 'task_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['task', '-created_at'], name='idx_activity_task_recent')],
            },
        ),
    ]
