# Generated by Django 5.2.17 on 2026-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_attachment_count_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='verb',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assignee_added', 'Assignee added'), ('assignee_removed', 'Assignee removed'), ('priority_changed', 'Priority changed'), ('due_date_changed', 'Due date changed'), ('renamed', 'Renamed'), ('moved', 'Moved'), ('completed', 'Completed'), ('deleted', 'Deleted'), ('restored', 'Restored'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed')], db_index=True, max_length=32),
        ),
    ]
