# Generated by Django 5.2.17 on 2026-08-07 12:10

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(db_collation='C', db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#7B68EE', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('is_private', models.BooleanField(default=False)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_spaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spaces',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(db_collation='C', db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#7B68EE', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='workspaces.space')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StatusSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default', max_length=80)),
                ('space', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='workspaces.space')),
            ],
            options={
                'db_table': 'status_sets',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='#87909E', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('type', models.CharField(choices=[('open', 'Not started'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='open', max_length=8)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('status_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='workspaces.statusset')),
            ],
            options={
                'db_table': 'statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(db_collation='C', db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#7B68EE', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('default_view', models.CharField(choices=[('list', 'List'), ('board', 'Board')], default='list', max_length=8)),
                ('task_count', models.PositiveIntegerField(default=0)),
                ('open_task_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lists', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='workspaces.folder')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='workspaces.space')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'db_table': 'lists',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='statusset',
            name='list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='workspaces.tasklist'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#7B68EE', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-F]{6}$', 'Must be an uppercase #RRGGBB hex colour.')])),
                ('avatar', models.ImageField(blank=True, max_length=500, null=True, upload_to='workspaces/%Y/%m/')),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='space',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], default='member', max_length=10)),
                ('token', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], db_index=True, default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workspaces.workspace')),
            ],
            options={
                'db_table': 'workspace_members',
                'ordering': ['role', 'user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['space', 'archived', 'position'], name='idx_folder_space_arch_pos'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(models.F('space'), django.db.models.functions.text.Lower('name'), name='uniq_folder_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('space', 'position'), name='uniq_folder_position_per_space'),
        ),
        migrations.AddIndex(
            model_name='status',
            index=models.Index(fields=['status_set', 'order'], name='idx_status_set_order'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(models.F('status_set'), django.db.models.functions.text.Lower('name'), name='uniq_status_name_per_set'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('status_set', 'order'), name='uniq_status_order_per_set'),
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('status_set',), name='uniq_default_status_per_set'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['space', 'folder', 'position'], name='idx_list_space_folder_pos'),
        ),
        migrations.AddIndex(
            model_name='tasklist',
            index=models.Index(fields=['space', 'archived'], name='idx_list_space_arch'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(models.F('folder'), django.db.models.functions.text.Lower('name'), condition=models.Q(('folder__isnull', False)), name='uniq_list_name_per_folder'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(models.F('space'), django.db.models.functions.text.Lower('name'), condition=models.Q(('folder__isnull', True)), name='uniq_list_name_per_space_root'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('folder', 'position'), name='uniq_list_position_per_folder'),
        ),
        migrations.AddConstraint(
            model_name='tasklist',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', True)), fields=('space', 'position'), name='uniq_list_position_per_space_root'),
        ),
        migrations.AddConstraint(
            model_name='statusset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('list__isnull', True), ('space__isnull', False)), models.Q(('list__isnull', False), ('space__isnull', True)), _connector='OR'), name='statusset_exactly_one_owner'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['owner'], name='idx_ws_owner'),
        ),
        migrations.AddIndex(
            model_name='space',
            index=models.Index(fields=['workspace', 'archived', 'position'], name='idx_space_ws_arch_pos'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('name'), name='uniq_space_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='space',
            constraint=models.UniqueConstraint(fields=('workspace', 'position'), name='uniq_space_position_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['workspace', 'status'], name='idx_invite_ws_status'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(django.db.models.functions.text.Lower('email'), name='idx_invite_email_ci'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('email'), condition=models.Q(('status', 'pending')), name='uniq_pending_invite_per_email_per_ws'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['workspace', 'role'], name='idx_member_ws_role'),
        ),
        migrations.AddIndex(
            model_name='workspacemember',
            index=models.Index(fields=['user', 'workspace'], name='idx_member_user_ws'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='uniq_member_per_workspace'),
        ),
    ]
