# Generated by Django 5.2.17 on 2026-08-10 04:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='permissions_version',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', "A'zo"), ('guest', 'Mehmon')], db_index=True, max_length=10)),
                ('permission', models.CharField(db_index=True, max_length=64)),
                ('allowed', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'rol ruxsati',
                'verbose_name_plural': 'rol ruxsatlari',
                'db_table': 'workspace_role_permissions',
                'ordering': ['role', 'permission'],
                'indexes': [models.Index(fields=['workspace', 'role'], name='idx_roleperm_ws_role')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'role', 'permission'), name='uniq_role_permission_per_workspace'), models.CheckConstraint(condition=models.Q(('role', 'owner'), _negated=True), name='role_permission_never_owner')],
            },
        ),
        migrations.CreateModel(
            name='SpaceMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.CharField(choices=[('viewer', "Ko'ruvchi"), ('contributor', 'Ishtirokchi'), ('manager', 'Menejer (PM)')], db_index=True, default='contributor', max_length=12)),
                ('source', models.CharField(choices=[('manual', "Qo'lda"), ('auto_creator', 'Avto (yaratuvchi)'), ('auto_assignee', 'Avto (biriktirilgan)'), ('backfill', 'Migratsiya')], default='manual', max_length=14)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_members', to='workspaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "bo'lim a'zosi",
                'verbose_name_plural': "bo'lim a'zolari",
                'db_table': 'space_members',
                'ordering': ['access', 'user__email'],
                'indexes': [models.Index(fields=['user', 'space'], name='idx_spacemember_user_space'), models.Index(fields=['space', 'access'], name='idx_spacemember_space_access')],
                'constraints': [models.UniqueConstraint(fields=('space', 'user'), name='uniq_space_member')],
            },
        ),
    ]
